Change rotate props
tscircuit/jscad-fiber pull request #39
Opened 2024-07-26 08:19 UTC by Slaviiiii

2024-07-26 14:06 UTC, seveibar requested changes
We discussed "generous acceptance" which means accepting both values, look at Translate

2024-07-26 16:05 UTC, Slaviiiii commented
I do not think we are using rotation anywhere, right?
I currently am using it for another issue, but I could change the property to angles with the package update because there aren't any other repos using it.

2024-07-26 16:46 UTC, seveibar commented
@Slaviiiii we should accept both `rotation` and `angles` in the `<Rotate />` component

2024-07-27 16:38 UTC, seveibar approved these changes

2024-07-27 16:40 UTC, merged